version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Node.js backend service
  server:
    build:
      context: ./server
    container_name: chat_server
    environment:
      - MONGODB_URI=mongodb://mongo:27017/realtime-chat
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./server:/usr/src/app

  # React frontend service
  client:
    build:
      context: ./client
    container_name: chat_frontend
    ports:
      - "8080:80"
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app

volumes:
  mongo-data:
    driver: local